name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "wyff123"
database_id = "16b53bf1-a786-4875-944e-3e5fe5c68bad"
